In [ ]:
#| default_exp reading
%load_ext autoreload
%autoreload 2

import sys
from fastcore.xtras import Path

In [ ]:
#| hide
# Insert in Path Project Directory
sys.path.insert(0, str(Path().cwd().parent))

# Leitura
> Este módulo concentra funções para a leitura dos diversos arquivos que compõe a base de dados

* `STEL` - Serviços Privados de Telecomunicações
* `RADCOM` - Serviço de Radiodifusão Comunitária
* `MOSAICO` - Demais serviços de Radiodifusão, e.g. TV, RTV, FM, AM, etc.
* `AERONAUTICA` - Consolidação de diversas bases de dados públicas da aeronáutica

In [ ]:
# | export
from pathlib import Path
import json
from pprint import pprint as pp

import pandas as pd
from dotenv import find_dotenv, load_dotenv


load_dotenv(find_dotenv())

True

## MOSAICO
> O mosaico atualmente é composto por 2 bases complementares originárias de um banco `MongoDB`: 

-  `Estações`
- `Plano Básico`

In [ ]:
#|eval: false
#|code_fold: true
folder = Path.cwd().parent / 'extracao' / 'datasources' / 'arquivos' / 'saida'

In [ ]:
#|eval: false
#|code_fold: true

def read_df(name: str)->pd.DataFrame:
    return pd.read_parquet(folder / f'{name}.parquet', dtype_backend='numpy_nullable')

In [ ]:
df = read_df('estacoes')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073189 entries, 0 to 1073188
Data columns (total 29 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   Frequência                   1073189 non-null  category
 1   Entidade                     1073189 non-null  category
 2   Fistel                       1073189 non-null  category
 3   Serviço                      1073189 non-null  category
 4   Estação                      1073189 non-null  category
 5   Latitude                     1073189 non-null  category
 6   Longitude                    1073189 non-null  category
 7   Código_Município             1073189 non-null  category
 8   Município                    1073189 non-null  category
 9   UF                           1073189 non-null  category
 10  Classe                       1073189 non-null  category
 11  Classe_Emissão               1073189 non-null  category
 12  Largura_Emissão(kHz)         1073189 non-null  category
 13  Validade_RF                  1073189 non-null  category
 14  Status                       1073189 non-null  category
 15  Fonte                        1073189 non-null  category
 16  Multiplicidade               1073189 non-null  category
 17  Log                          1073189 non-null  category
 18  Cota_Base_Torre(m)           1073189 non-null  category
 19  Potência_Transmissor(W)      1073189 non-null  category
 20  Ganho_Antena(dBd)            1073189 non-null  category
 21  Ângulo_Elevação_Antena       1073189 non-null  category
 22  Azimute_Antena               1073189 non-null  category
 23  Altura_Antena(m)             1073189 non-null  category
 24  Atenuação_Linha(db/100m)     1073189 non-null  category
 25  Perdas_Acessórias_Linha(db)  1073189 non-null  category
 26  Padrão_Antena(dBd)           1073189 non-null  category
 27  Comprimento_Linha(m)         1073189 non-null  category
 28  Relatório_Canal              1073189 non-null  category
dtypes: category(29)
memory usage: 102.8 MB

In [ ]:
df = df.astype('string', copy=False)

In [ ]:
for c in df.columns:
	df.loc[df[c] == '', c] = '-1'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073189 entries, 0 to 1073188
Data columns (total 29 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   Frequência                   1073189 non-null  category
 1   Entidade                     1073189 non-null  category
 2   Fistel                       1073189 non-null  category
 3   Serviço                      1073189 non-null  category
 4   Estação                      1073189 non-null  category
 5   Latitude                     1073189 non-null  category
 6   Longitude                    1073189 non-null  category
 7   Código_Município             1073189 non-null  category
 8   Município                    1073189 non-null  string
 9   UF                           1073189 non-null  category
 10  Classe                       1073189 non-null  category
 11  Classe_Emissão               1073189 non-null  string
 12  Largura_Emissão(kHz)         1073189 non-null  category
 13  Validade_RF                  1073189 non-null  category
 14  Status                       1073189 non-null  category
 15  Fonte                        1073189 non-null  category
 16  Multiplicidade               1073189 non-null  category
 17  Log                          1073189 non-null  category
 18  Cota_Base_Torre(m)           1073189 non-null  category
 19  Potência_Transmissor(W)      1073189 non-null  category
 20  Ganho_Antena(dBd)            1073189 non-null  category
 21  Ângulo_Elevação_Antena       1073189 non-null  category
 22  Azimute_Antena               1073189 non-null  category
 23  Altura_Antena(m)             1073189 non-null  category
 24  Atenuação_Linha(db/100m)     1073189 non-null  category
 25  Perdas_Acessórias_Linha(db)  1073189 non-null  category
 26  Padrão_Antena(dBd)           1073189 non-null  category
 27  Comprimento_Linha(m)         1073189 non-null  category
 28  Relatório_Canal              1073189 non-null  category
dtypes: category(27), string(2)
memory usage: 116.0 MB

In [ ]:
# df = df.astype('string', copy=False).fillna('-1').astype('category')
df.astype('category').to_parquet(folder / 'estacoes.parquet', index=False, compression='gzip')

In [ ]:
i = df.loc[:, ['Frequência', 'Entidade', 'Serviço', 'Estação', 'Classe_Emissão', 'Largura_Emissão(kHz)', 'Log']].sample()
pp(eval(i.Log.item()))

[{'Coluna': 'Designação_Emissão',
  'Original': '10M0G7W',
  'Processamento': 'Registro expandido nos componentes individuais '
                   'Largura_Emissão(kHz) e Classe_Emissão'},
 {'Coluna': '#Estação',
  'Original': '[689665024, 689665024, 689665024, 1000452147, 1000452147, '
              '1000452147, 1000455278, 1000455278, 1000455278]',
  'Processamento': 'Registro agrupado. Colunas consideradas: '
                   "['Código_Município', 'Fistel', 'Frequência', "
                   "'Largura_Emissão(kHz)', 'Classe_Emissão', 'Tecnologia']"},
 {'Processamento': 'Colunas criadas à partir da Canalização do Serviço: '
                   "['Início_Canal_Down', 'Fim_Canal_Down', 'Blocos_Downlink', "
                   "'Faixas', 'Canalização', 'Offset']"},
 {'Processamento': 'Criada Frequência de Recepção (Uplink) à partir do '
                   'Downlink e Offset.'},
 {'Coluna': 'Latitude',
  'Original': '-16.5662',
  'Processamento': 'Substituição por Coordenadas do Município (Agrupamento '
                   'SMP)'},
 {'Coluna': 'Longitude',
  'Original': '-42.8923',
  'Processamento': 'Substituição por Coordenadas do Município (Agrupamento '
                   'SMP)'},
 {'Coluna': '#Município',
  'Original': 'GRÃO MOGOL',
  'Processamento': 'Coluna Município normalizada como consta no IBGE.'}]

In [ ]:
df[df.Log.str.contains("MOGOL")]

,Frequência,Entidade,Fistel,Serviço,Estação,Latitude,Longitude,Código_Município,Município,UF,...,Potência_Transmissor(W),Ganho_Antena(dBd),Ângulo_Elevação_Antena,Azimute_Antena,Altura_Antena(m),Atenuação_Linha(db/100m),Perdas_Acessórias_Linha(db),Padrão_Antena(dBd),Comprimento_Linha(m),Relatório_Canal
425890,257.95,Oi S.a. - em Recuperacao Judicial,50437505960,019,1014695756,-16.55204444,-42.87386667,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
436002,258.625,Oi S.a. - em Recuperacao Judicial,50437505960,019,1015515840,-16.55194444,-42.87416667,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
444836,259.225,Oi S.a. - em Recuperacao Judicial,50437505960,019,1015515840,-16.55194444,-42.87416667,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
591996,733.0,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
591997,733.0,TELEFONICA BRASIL S.A.,50409146285,010,1000452147,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
611077,788.0,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
611078,788.0,TELEFONICA BRASIL S.A.,50409146285,010,1000452147,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
622692,829.5,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
622693,829.5,TELEFONICA BRASIL S.A.,50409146285,010,693077662,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
653685,874.5,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
653686,874.5,TELEFONICA BRASIL S.A.,50409146285,010,693077662,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
687363,908.75,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
697279,953.75,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
710035,1717.5,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
710036,1717.5,TELEFONICA BRASIL S.A.,50409146285,010,693077662,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
751482,1780.0,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
751483,1780.0,TELEFONICA BRASIL S.A.,50409146285,010,693077662,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
762725,1812.5,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
762726,1812.5,TELEFONICA BRASIL S.A.,50409146285,010,693077662,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
823193,1875.0,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
823194,1875.0,TELEFONICA BRASIL S.A.,50409146285,010,693077662,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
853051,1962.5,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
885995,2152.5,TELEFONICA BRASIL S.A.,50409146285,010,689665024,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
902938,2560.0,TELEFONICA BRASIL S.A.,50409146285,010,693077662,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
914205,2680.0,TELEFONICA BRASIL S.A.,50409146285,010,693077662,-16.5662,-42.8923,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
942844,6460.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
942845,6460.0,TELEFONICA BRASIL S.A.,50417179405,019,1014771037,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
944720,6500.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
946073,6540.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
947585,6580.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
948699,6610.0,TELEFONICA BRASIL S.A.,50417179405,019,1014771037,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
949098,6620.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
950087,6640.0,TELEFONICA BRASIL S.A.,50417179405,019,1014771037,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
950563,6660.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
951897,6700.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
953462,6740.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
954523,6800.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695535,-16.302556,-42.708636,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
956389,6840.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695535,-16.302556,-42.708636,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
956396,6840.0,TELEFONICA BRASIL S.A.,50417179405,019,1014771037,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
957734,6880.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695535,-16.302556,-42.708636,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
959238,6920.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695535,-16.302556,-42.708636,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
960751,6960.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695535,-16.302556,-42.708636,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
962211,7000.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695535,-16.302556,-42.708636,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
963538,7040.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695535,-16.302556,-42.708636,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
965100,7080.0,TELEFONICA BRASIL S.A.,50417179405,019,1014695535,-16.302556,-42.708636,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
970943,7526.0,TELEFONICA BRASIL S.A.,50417179405,019,1014802773,-16.691361,-43.100528,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
972314,7554.0,TELEFONICA BRASIL S.A.,50417179405,019,1014802773,-16.691361,-43.100528,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
986622,7866.3,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
988253,7895.95,TELEFONICA BRASIL S.A.,50417179405,019,1014695543,-16.552,-42.874358,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
992173,8059.02,TELEFONICA BRASIL S.A.,50417179405,019,1008828642,-16.416667,-43.227239,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
993947,8088.67,TELEFONICA BRASIL S.A.,50417179405,019,1008828642,-16.416667,-43.227239,3127800,Grão Mogol,MG,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [ ]:
from extracao.constants import AGG_LICENCIAMENTO

In [ ]:
grouped = df.groupby(AGG_LICENCIAMENTO, dropna=True, sort=False, observed=True)

In [ ]:
grouped_stations = grouped['Estação']

In [ ]:
df_sub = df.dropna(subset=AGG_LICENCIAMENTO).reset_index(drop=True)

In [ ]:
df_sub

,_id,Fistel,Serviço,Entidade,UF,Estação,Classe,Latitude,Longitude,Município,Código_Município,Num_Ato,Validade_RF,Frequência,Tipo_Estação,Tecnologia,Log,Largura_Emissão(kHz),Classe_Emissão
0,6337604c530fc,50402602889,011,Cricom do Brasil Ltda,PR,1002522193,ML,-25.408333333333335,-49.255277777777664,Curitiba,4106902,501362016,2035-11-11,459.25,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1W
1,6337604c58a20,50402602889,011,Cricom do Brasil Ltda,PR,1002522193,ML,-25.408333333333335,-49.255277777777664,Curitiba,4106902,501362016,2035-11-11,469.125,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1W
2,6337604e5c24a,50403060400,011,LOOPCOM COMERCIO E SERVICOS LTDA - ME,SP,1008389304,ML,-23.630013888888833,-46.52363888888883,Santo André,3547809,26672019,2036-03-29,383.125,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1E
3,6337604f66b99,50403738725,011,JEVIN COMERCIO E SERVIÇOS LTDA,RJ,1009950832,ML,-22.376113888888835,-41.79130833333333,Macaé,3302403,47952022,2026-11-21,383.85,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1D
4,6337604f6fd0a,50403738725,011,JEVIN COMERCIO E SERVIÇOS LTDA,RJ,1012366712,ML,-21.867583333333332,-41.0012805555555,São João da Barra,3305000,47952022,2026-11-21,459.5875,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6813009,f698d5f802581547,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,22212023,2028-11-29,1875.0,base,GSM,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",200.0,G7W
6813010,f698d5f802581549,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,22212023,2028-11-29,874.5,base,WCDMA,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",5000.0,G9W
6813011,f698d5f80258154b,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,77872023,2028-11-29,2130.0,base,WCDMA,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",5000.0,G9W
6813012,f698d5f80258154d,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,22212023,2028-11-29,1875.0,base,LTE,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",10000.0,G7W
6813013,f698d5f80258154f,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,77872023,2028-11-29,2130.0,base,LTE,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",10000.0,G7W

In [ ]:
grouped_stations = grouped_stations.agg(lambda x: ', '.join(list(x)))

In [ ]:
grouped_stations.values[0]

'1002522193, 691399310, 691399328, 691399336, 691399344, 691399352, 691399360, 691399379, 691399387, 691399395, 691399409, 691399417, 691399425, 691399433, 691399441, 691399450, 691399468, 691399476, 691399484, 691399492, 691399506, 691399514, 691399522, 691399530, 691399549, 691399557, 691399565, 691399573, 691399581, 691399590, 691399603, 691399611, 691399620, 691399638, 691399646, 691399654, 691399662, 691399670, 691399689, 691399697, 691399700, 691399719, 691399727, 691399735, 691399743, 691399751, 691399760, 691399778, 691399786, 691399794, 691399808, 691399816, 691399824, 691399832, 691399840, 691399859, 691399867, 691399875, 691399883, 691399891, 691399905, 691399913, 691399921, 691399930, 691399948, 691399956, 691399964, 691399972, 691399980, 691399999, 691400008, 691400016, 691400024, 691400032, 691400040, 691400059, 691400067, 691400075, 691400083, 691400091, 691400105, 691400113, 691400121, 691400130, 691400148, 691400156, 691400164, 691400172, 691400180, 691400199, 691400202, 691400210, 691400229, 691400237, 691400245, 691400253, 691400261, 691400270, 691400288, 691400296, 691400300, 691401314, 691401322, 691401330, 691401349, 691401357, 691401365, 691401373, 691401381, 691401390, 691401403, 691401411, 691401420, 691401438, 691401446, 691401454, 691401462, 691401470, 691401489, 691401497, 691401500, 691401519, 691401527, 691401535, 691401543, 691401551, 691401560, 691401578, 691401586, 691401594, 691401608, 691401616, 691401624, 691401632, 691401640, 691401659, 691401667, 691401675, 691401683, 691401691, 691401705, 691401713, 691401721, 691401730, 691401748, 691401756, 691401764, 691401772, 691401780, 691401799, 691401802, 1002522711, 1002522720, 1002522738, 1002522746, 1002522754, 1002522762, 1002522770, 1002522789, 1002522797, 1002522800, 1002522819, 1002522827, 1002522835, 1002522843, 1002522851, 1002522860, 1002522878, 1002522886, 1002522894'

:

In [ ]:
df_sub

,_id,Fistel,Serviço,Entidade,UF,Estação,Classe,Latitude,Longitude,Município,Código_Município,Num_Ato,Validade_RF,Frequência,Tipo_Estação,Tecnologia,Log,Largura_Emissão(kHz),Classe_Emissão,#Estação
0,6337604c530fc,50402602889,011,Cricom do Brasil Ltda,PR,1002522193,ML,-25.408333333333335,-49.255277777777664,Curitiba,4106902,501362016,2035-11-11,459.25,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1W,889153
1,6337604c58a20,50402602889,011,Cricom do Brasil Ltda,PR,1002522193,ML,-25.408333333333335,-49.255277777777664,Curitiba,4106902,501362016,2035-11-11,469.125,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1W,889004
2,6337604e5c24a,50403060400,011,LOOPCOM COMERCIO E SERVICOS LTDA - ME,SP,1008389304,ML,-23.630013888888833,-46.52363888888883,Santo André,3547809,26672019,2036-03-29,383.125,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1E,889152
3,6337604f66b99,50403738725,011,JEVIN COMERCIO E SERVIÇOS LTDA,RJ,1009950832,ML,-22.376113888888835,-41.79130833333333,Macaé,3302403,47952022,2026-11-21,383.85,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1D,"888993, 889010, 5816461, 5816462, 5816463, 581..."
4,6337604f6fd0a,50403738725,011,JEVIN COMERCIO E SERVIÇOS LTDA,RJ,1012366712,ML,-21.867583333333332,-41.0012805555555,São João da Barra,3305000,47952022,2026-11-21,459.5875,movelml,<NA>,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",7.6,F1W,889155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6813009,f698d5f802581547,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,22212023,2028-11-29,1875.0,base,GSM,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",200.0,G7W,NaN
6813010,f698d5f802581549,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,22212023,2028-11-29,874.5,base,WCDMA,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",5000.0,G9W,NaN
6813011,f698d5f80258154b,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,77872023,2028-11-29,2130.0,base,WCDMA,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",5000.0,G9W,NaN
6813012,f698d5f80258154d,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,22212023,2028-11-29,1875.0,base,LTE,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",10000.0,G7W,NaN
6813013,f698d5f80258154f,04030023541,175,ALGAR TELECOM S/A,MG,1015574944,FB,-18.871461,-48.294458,UBERLANDIA,3170206,77872023,2028-11-29,2130.0,base,LTE,"[{""Coluna"": ""Designação_Emissão"", ""Processamen...",10000.0,G7W,NaN

In [ ]:
len(grouped_stations.groups.values())

289896